In [1]:
import torch

In [2]:
x = torch.ones(2, 2, requires_grad=True)
print(x)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


In [3]:
y = x + 2
y

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward>)

In [4]:
print(y.grad_fn)

In [5]:
z = y * y * 3
out = z.mean()
print(z, out)

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward>) tensor(27., grad_fn=<MeanBackward1>)


In [6]:
a = torch.randn(2, 2)
a = ((a*3)/(a-1))
print(a.required_grad)

AttributeError: 'Tensor' object has no attribute 'required_grad'

In [8]:
a.requires_grad_(True)

tensor([[ 1.4839,  0.5918],
        [ 0.8606, -2.5783]], requires_grad=True)

In [10]:
print(a.requires_grad_)

<built-in method requires_grad_ of Tensor object at 0x10e6a1288>


In [12]:
b = (a**2).sum()
print(b.grad_fn)

In [13]:
out

tensor(27., grad_fn=<MeanBackward1>)

In [14]:
out.backward()

In [15]:
print(x)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


In [17]:
print(x.grad)

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])


In [18]:
x = torch.randn(3, requires_grad=True)

y = x * 2
while y.data.norm() < 1000:
    y = y*2

print(y)

tensor([  70.6755, -171.9521, 1027.9415], grad_fn=<MulBackward>)


In [19]:
gradients = torch.tensor([0.1, 1.0, 0.0001], dtype = torch.float)
y.backward(gradients)


In [20]:
print(x.grad)

tensor([ 102.4000, 1024.0000,    0.1024])
